// <auto-generated />
using System;
using GazAvtoMaster.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GazAvtoMaster.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GazAvtoMaster.API.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("action");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("changes_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("employee_name");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.HasKey("Id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("GazAvtoMaster.API.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand_name");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.HasKey("BrandId");

                    b.ToTable("brands", (string)null);

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            BrandName = "LADA (ВАЗ)",
                            Country = "Россия"
                        },
                        new
                        {
                            BrandId = 2,
                            BrandName = "GAZ (ГАЗ)",
                            Country = "Россия"
                        },
                        new
                        {
                            BrandId = 3,
                            BrandName = "UAZ (УАЗ)",
                            Country = "Россия"
                        },
                        new
                        {
                            BrandId = 4,
                            BrandName = "Toyota",
                            Country = "Япония"
                        },
                        new
                        {
                            BrandId = 5,
                            BrandName = "Hyundai",
                            Country = "Корея"
                        },
                        new
                        {
                            BrandId = 6,
                            BrandName = "KIA",
                            Country = "Корея"
                        },
                        new
                        {
                            BrandId = 7,
                            BrandName = "Volkswagen",
                            Country = "Германия"
                        },
                        new
                        {
                            BrandId = 8,
                            BrandName = "Skoda",
                            Country = "Чехия"
                        },
                        new
                        {
                            BrandId = 9,
                            BrandName = "Renault",
                            Country = "Франция"
                        },
                        new
                        {
                            BrandId = 10,
                            BrandName = "Nissan",
                            Country = "Япония"
                        });
                });

            modelBuilder.Entity("GazAvtoMaster.API.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("car_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CarId"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrival_date");

                    b.Property<int?>("CarModelModelId")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer")
                        .HasColumnName("model_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("price");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character(17)")
                        .HasColumnName("vin")
                        .IsFixedLength();

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("CarId");

                    b.HasIndex("CarModelModelId");

                    b.HasIndex("ModelId");

                    b.HasIndex("StatusId");

                    b.ToTable("cars", (string)null);
                });

            modelBuilder.Entity("GazAvtoMaster.API.Models.CarModel", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("model_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModelId"));

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("body_type");

                    b.Property<int>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<decimal>("EngineVol")
                        .HasColumnType("decimal(3,1)")
                        .HasColumnName("engine_vol");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("fuel_type");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.HasKey("ModelId");

                    b.HasIndex("BrandId");

                    b.ToTable("models", (string)null);

                    b.HasData(
                        new
                        {
                            ModelId = 1,
                            BodyType = "Седан",
                            BrandId = 1,
                            EngineVol = 1.6m,
                            FuelType = "Бензин",
                            ModelName = "Vesta"
                        },
                        new
                        {
                            ModelId = 2,
                            BodyType = "Седан",
                            BrandId = 1,
                            EngineVol = 1.6m,
                            FuelType = "Бензин",
                            ModelName = "Granta"
                        },
                        new
                        {
                            ModelId = 3,
                            BodyType = "Внедорожник",
                            BrandId = 1,
                            EngineVol = 1.7m,
                            FuelType = "Бензин",
                            ModelName = "Niva Legend"
                        },
                        new
                        {
                            ModelId = 4,
                            BodyType = "Кроссовер",
                            BrandId = 1,
                            EngineVol = 1.6m,
                            FuelType = "Бензин",
                            ModelName = "XRAY"
                        },
                        new
                        {
                            ModelId = 5,
                            BodyType = "Микроавтобус",
                            BrandId = 2,
                            EngineVol = 2.7m,
                            FuelType = "Бензин",
                            ModelName = "Газель Next"
                        },
                        new
                        {
                            ModelId = 6,
                            BodyType = "Микроавтобус",
                            BrandId = 2,
                            EngineVol = 2.3m,
                            FuelType = "Бензин",
                            ModelName = "Sobol"
                        },
                        new
                        {
                            ModelId = 7,
                            BodyType = "Внедорожник",
                            BrandId = 3,
                            EngineVol = 2.7m,
                            FuelType = "Бензин",
                            ModelName = "Patriot"
                        },
                        new
                        {
                            ModelId = 8,
                            BodyType = "Внедорожник",
                            BrandId = 3,
                            EngineVol = 2.7m,
                            FuelType = "Бензин",
                            ModelName = "Hunter"
                        },
                        new
                        {
                            ModelId = 9,
                            BodyType = "Седан",
                            BrandId = 4,
                            EngineVol = 2.5m,
                            FuelType = "Бензин",
                            ModelName = "Camry"
                        },
                        new
                        {
                            ModelId = 10,
                            BodyType = "Кроссовер",
                            BrandId = 4,
                            EngineVol = 2.0m,
                            FuelType = "Бензин",
                            ModelName = "RAV4"
                        },
                        new
                        {
                            ModelId = 11,
                            BodyType = "Внедорожник",
                            BrandId = 4,
                            EngineVol = 4.0m,
                            FuelType = "Бензин",
                            ModelName = "Land Cruiser"
                        },
                        new
                        {
                            ModelId = 12,
                            BodyType = "Седан",
                            BrandId = 5,
                            EngineVol = 1.6m,
                            FuelType = "Бензин",
                            ModelName = "Solaris"
                        },
                        new
                        {
                            ModelId = 13,
                            BodyType = "Кроссовер",
                            BrandId = 5,
                            EngineVol = 1.6m,
                            FuelType = "Бензин",
                            ModelName = "Creta"
                        },
                        new
                        {
                            ModelId = 14,
                            BodyType = "Кроссовер",
                            BrandId = 5,
                            EngineVol = 2.0m,
                            FuelType = "Бензин",
                            ModelName = "Tucson"
                        },
                        new
                        {
                            ModelId = 15,
                            BodyType = "Седан",
                            BrandId = 6,
                            EngineVol = 1.6m,
                            FuelType = "Бензин",
                            ModelName = "Rio"
                        },
                        new
                        {
                            ModelId = 16,
                            BodyType = "Кроссовер",
                            BrandId = 6,
                            EngineVol = 2.0m,
                            FuelType = "Бензин",
                            ModelName = "Sportage"
                        },
                        new
                        {
                            ModelId = 17,
                            BodyType = "Седан",
                            BrandId = 6,
                            EngineVol = 2.5m,
                            FuelType = "Бензин",
                            ModelName = "K5"
                        },
                        new
                        {
                            ModelId = 18,
                            BodyType = "Седан",
                            BrandId = 7,
                            EngineVol = 1.6m,
                            FuelType = "Бензин",
                            ModelName = "Polo"
                        },
                        new
                        {
                            ModelId = 19,
                            BodyType = "Кроссовер",
                            BrandId = 7,
                            EngineVol = 2.0m,
                            FuelType = "Бензин",
                            ModelName = "Tiguan"
                        },
                        new
                        {
                            ModelId = 20,
                            BodyType = "Седан",
                            BrandId = 8,
                            EngineVol = 1.4m,
                            FuelType = "Бензин",
                            ModelName = "Octavia"
                        },
                        new
                        {
                            ModelId = 21,
                            BodyType = "Лифтбек",
                            BrandId = 8,
                            EngineVol = 1.6m,
                            FuelType = "Бензин",
                            ModelName = "Rapid"
                        },
                        new
                        {
                            ModelId = 22,
                            BodyType = "Седан",
                            BrandId = 9,
                            EngineVol = 1.6m,
                            FuelType = "Бензин",
                            ModelName = "Logan"
                        },
                        new
                        {
                            ModelId = 23,
                            BodyType = "Кроссовер",
                            BrandId = 9,
                            EngineVol = 2.0m,
                            FuelType = "Бензин",
                            ModelName = "Duster"
                        },
                        new
                        {
                            ModelId = 24,
                            BodyType = "Кроссовер",
                            BrandId = 10,
                            EngineVol = 2.0m,
                            FuelType = "Бензин",
                            ModelName = "Qashqai"
                        },
                        new
                        {
                            ModelId = 25,
                            BodyType = "Кроссовер",
                            BrandId = 10,
                            EngineVol = 2.5m,
                            FuelType = "Бензин",
                            ModelName = "X-Trail"
                        });
                });

            modelBuilder.Entity("GazAvtoMaster.API.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("address");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character(6)")
                        .HasColumnName("passport_number")
                        .IsFixedLength();

                    b.Property<string>("PassportSeries")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character(4)")
                        .HasColumnName("passport_series")
                        .IsFixedLength();

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("patronymic");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.HasKey("ClientId");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("GazAvtoMaster.API.Models.Deal", b =>
                {
                    b.Property<int>("DealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("deal_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DealId"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer")
                        .HasColumnName("car_id");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("DealDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deal_date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("final_price");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("payment_type");

                    b.HasKey("DealId");

                    b.HasIndex("CarId");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("deals", (string)null);
                });

            modelBuilder.Entity("GazAvtoMaster.API.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hire_date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("patronymic");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("EmployeeId");

                    b.HasIndex("RoleId");

                    b.ToTable("employees", (string)null);

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Email = "zashekanec2010@gmail.com",
                            FirstName = "Илья",
                            HireDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Занин",
                            Login = "admin",
                            Password = "$2a$11$5Ba2UJPbEC5s6aecWLoFf.Tk.JJ0jldkDzN9lx/oVcxnAtIRC3XHi",
                            Patronymic = "Иванович",
                            Phone = "79998887766",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("GazAvtoMaster.API.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("reservation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReservationId"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer")
                        .HasColumnName("car_id");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<decimal>("Deposit")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("deposit");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reservation_date");

                    b.HasKey("ReservationId");

                    b.HasIndex("CarId");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("GazAvtoMaster.API.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Администратор"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Сотрудник"
                        });
                });

            modelBuilder.Entity("GazAvtoMaster.API.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId");

                    b.ToTable("statuses", (string)null);

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            StatusName = "В наличии"
                        },
                        new
                        {
                            StatusId = 2,
                            StatusName = "Зарезервирован"
                        },
                        new
                        {
                            StatusId = 3,
                            StatusName = "Продан"
                        });
                });

            modelBuilder.Entity("GazAvtoMaster.API.Models.TestDrive", b =>
                {
                    b.Property<int>("TdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("td_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TdId"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer")
                        .HasColumnName("car_id");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<string>("Feedback")
                        .HasColumnType("text")
                        .HasColumnName("feedback");

                    b.Property<DateTime>("TdDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("td_date");

                    b.HasKey("TdId");

                    b.HasIndex("CarId");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("test_drives", (string)null);
                });

            modelBuilder.Entity("GazAvtoMaster.API.Models.Car", b =>
                {
                    b.HasOne("GazAvtoMaster.API.Models.CarModel", null)
                        .WithMany("Cars")
                        .HasForeignKey("CarModelModelId");

                    b.HasOne("GazAvtoMaster.API.Models.CarModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GazAvtoMaster.API.Models.Status", "Status")
                        .WithMany("Cars")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("GazAvtoMaster.API.Models.CarModel", b =>
                {
                    b.HasOne("GazAvtoMaster.API.Models.Brand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("GazAvtoMaster.API.Models.Deal", b =>
                {
                    b.HasOne("GazAvtoMaster.API.Models.Car", "Car")
                        .WithMany("Deals")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GazAvtoMaster.API.Models.Client", "Client")
                        .WithMany("Deals")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GazAvtoMaster.API.Models.Employee", "Employee")
                        .WithMany("Deals")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Client");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("GazAvtoMaster.API.Models.Employee", b =>
                {
                    b.HasOne("GazAvtoMaster.API.Models.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GazAvtoMaster.API.Models.Reservation", b =>
                {
                    b.HasOne("GazAvtoMaster.API.Models.Car", "Car")
                        .WithMany("Reservations")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GazAvtoMaster.API.Models.Client", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GazAvtoMaster.API.Models.Employee", "Employee")
                        .WithMany("Reservations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Client");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("GazAvtoMaster.API.Models.TestDrive", b =>
                {
                    b.HasOne("GazAvtoMaster.API.Models.Car", "Car")
                        .WithMany("TestDrives")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GazAvtoMaster.API.Models.Client", "Client")
                        .WithMany("TestDrives")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GazAvtoMaster.API.Models.Employee", "Employee")
                        .WithMany("TestDrives")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Client");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("GazAvtoMaster.API.Models.Brand", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("GazAvtoMaster.API.Models.Car", b =>
                {
                    b.Navigation("Deals");

                    b.Navigation("Reservations");

                    b.Navigation("TestDrives");
                });

            modelBuilder.Entity("GazAvtoMaster.API.Models.CarModel", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("GazAvtoMaster.API.Models.Client", b =>
                {
                    b.Navigation("Deals");

                    b.Navigation("Reservations");

                    b.Navigation("TestDrives");
                });

            modelBuilder.Entity("GazAvtoMaster.API.Models.Employee", b =>
                {
                    b.Navigation("Deals");

                    b.Navigation("Reservations");

                    b.Navigation("TestDrives");
                });

            modelBuilder.Entity("GazAvtoMaster.API.Models.Role", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("GazAvtoMaster.API.Models.Status", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
